### ISSUE TITLE
Maker EAE job - the FONT for the profile notes and process notes is in WHITE and can't be read

### ISSUE THREAD

**Issue by Macknizzle** [onlylions/suggestions#28]

**Comment by b3ntly** [comment]
Damn that does look shitty. I think whoever made the note in Salesforce chose a white font-color for the text. You'd have to change it back to black in that editor because the jobs page keeps whatever styling people choose. In the meantime you can highlight the text to at least read it.

I could override the styling on my end, but then people wouldn't be able to customize styling of the notes when they create/edit it themselves.
